### ISSUE TITLE
Feature Request: Comparison suggestion

### ISSUE THREAD

**Issue by TheAssmann** [aantipov/moiva-catalog#10]
Enter a package and get recommendations of similar packages to compare (based on comparisons of others).

This way Moiva also allows to discover valid alternatives for a given package

**Comment by aantipov** [comment]
Hi @TheAssmann 
Do you mean recommendations/suggestions similar to what Npmtrends is doing? 
![image](https://user-images.githubusercontent.com/427621/102707354-77f6ec80-429a-11eb-825c-e9629b611e1d.png)

**Comment by TheAssmann** [comment]
Oh, i didn't even know about npmtrends tbh 😅

Yes, i meant something exactly like this. If this is too far of the main idea of Moiva i can relate, though. I'll use npmtrends in this case.

Thanks!

**Comment by aantipov** [comment]
I implemented suggestions. Thanks for the feature request!
Pls let me know if you have any other feedback 😄

**Comment by TheAssmann** [comment]
Hi @aantipov 

awesome! Looks absolutely great! Thanks a bunch!
