### ISSUE TITLE
react framework is a combination of react and react-dom, comparison only accounts one

### ISSUE THREAD

**Issue by chiefjester** [aantipov/moiva-catalog#11]
Hey @aantipov 

Thanks for making this project, this is very promising!

For React, it's a combination of `react` (the library) and the `react-dom` (the renderer).

So I'm not sure how are you gonna factor that. Because if you check the comparison of the frameworks, it looks like React is very tiny which is a bit misleading. Since they just moved the renderer part to a different package (they used to be on a single package, like vue, preact, etc).

Anyway, thanks for making this, looking forward to its success.

**Comment by aantipov** [comment]
Hi Chris,

Thank you for your feedback.

I'm aware of the problem that you mentioned and I don't have any solid idea yet how to resolve it.
Maybe you or the community could come up with some nice ideas 😀

**Comment by aantipov** [comment]
Hi @thisguychris 

I fixed the issue a long ago. Thanks for reporting! 👍 
https://moiva.io/?npm=@angular/core+react+vue
![CleanShot 2021-08-04 at 13 12 40@2x](https://user-images.githubusercontent.com/427621/128164240-35122ce9-c7e5-460b-a430-c76c56857f1e.png)

Closing
