### ISSUE TITLE
bundlephobia?

### ISSUE THREAD

**Issue by testerez** [aantipov/moiva-catalog#2]
Cool tool! It could be nice to add data from https://bundlephobia.com/

**Comment by aantipov** [comment]
Thanks! Yep, adding comparison by bundle size is on my agenda.

**Comment by aantipov** [comment]
@testerez  I added comparison by bundle size. Pls let me know if you have any other suggestions 😄

**Comment by testerez** [comment]
This is great! If the data is actually coming from Bundlephobia, the labels on the graph could link to the bundlephobia pages so it's easy to get more info if needed.

**Comment by aantipov** [comment]
Thanks for the suggestion, it makes sense, I'll check what I can do.
The data are coming from Bundlephobia, yes
