### ISSUE TITLE
Put most popular packages on homepage

### ISSUE THREAD

**Issue by robole** [aantipov/moiva-catalog#4]
Having the most popular packages per different categories on the homepage would be helpful. Its something that is missing from NPM too!

You can look at [this post](https://blog.madza.dev/73-awesome-npm-packages-for-productivity) for some category ideas.

I wish you success with the project.

**Comment by aantipov** [comment]
@robole Thanks for the suggestion and the link. 
How would you like it to be implemented? Statically render such a list and make it clickable? 
Wouldn't autosuggestion solve the problem? 
You can check how [npmtrends](https://www.npmtrends.com/) implements it
![image](https://user-images.githubusercontent.com/427621/102391207-ae501580-3fd5-11eb-9ab6-3200fc27d3be.png)

**Comment by robole** [comment]
A static list would be a good start. You could add a dynamic list later based on stars/download..etc. for the biggest categories that you pick (or are the most searched).

Autosuggestion solves a different problem mostly. Autosuggestion is speeding up the process when you know what you're looking for, or are maybe unsure of the exact name. 

The use case is to find packages for doing "AJAX" or similar. 

Npmtrends only gives you information on related packages once you find a particular package. If I search for "fetch" and find that package. Then, the keywords under the search bar are related terms, but some are packages like axios. I don't know which is which.

![Screenshot from 2020-12-17 22-07-59](https://user-images.githubusercontent.com/3703647/102498113-85528200-40b4-11eb-93e3-da68645b4efe.png)

If I want to compare "AJAX" packages for popularity. Then I need to look in the related section, and it may have what I need.

![Screenshot from 2020-12-17 22-11-47](https://user-images.githubusercontent.com/3703647/102498686-42dd7500-40b5-11eb-83ae-950de2ee0935.png)

My suggestion to expose this as a feature. Give the list up front for "Popular AJAX packages".

**Comment by aantipov** [comment]
@robole Got it! Thanks a lot for the explanation. Will add the section

**Comment by aantipov** [comment]
@robole I implemented the feature. Thanks a lot for the suggestion, I think it's a nice feature 👍 
![image](https://user-images.githubusercontent.com/427621/102712266-0df13e00-42c0-11eb-9236-8f5e1db3de59.png)
