### ISSUE TITLE
Feature Request: Show TypeScript Definition Status

### ISSUE THREAD

**Issue by rblackman** [aantipov/moiva-catalog#5]
It would be really helpful to see the status of TypeScript definitions for a package. If there aren't definitions available, that becomes a huge consideration for a TS developer when evaluating if they should use a library.

I would propose three states for TS definitions:
* Unavailable/Unknown
* Bundled with Package
* Available from DefinitelyTyped

**Comment by aantipov** [comment]
Probably something we can use https://github.blog/changelog/2020-12-16-npm-displays-packages-with-bundled-typescript-declarations/

**Comment by aantipov** [comment]
Hi @rblackman 
I implemented the feature a long ago https://moiva.io/?npm=@angular/core+vue
Hence closing the issue
![CleanShot 2021-08-04 at 13 10 21@2x](https://user-images.githubusercontent.com/427621/128163897-caca1866-d8ed-417a-89ef-efa5caed23f9.png)
